### PR TITLE
allow for uploading to pypi

### PR DESCRIPTION
**Pull request by lucidrains**
should allow you to upload this to pypi

```bash
$ pip install twine
```

then

```bash
$ make upload_package
```

it will then ask for username and password, which you need to acquire by making an account at https://pypi.org/

### CODE REVIEW

**Comment by tridao** [comment]
Thank you Phil!

**Comment by robotcator** [comment]
Hi, @lucidrains, can this distinguish which Torch version and which Cuda version? It seems that the extension will compile with this setting.

**Comment by tridao** [comment]
I'm not certain but  I think `pip install flash-attn` is equivalent to cloning the repo and then run `python setup.py install`. So it would compile locally and use the local torch and cuda version?

**Comment by lucidrains** [comment]
@robotcator yup, what Tri said

may also throw in a check at some point to make sure it only compiles for the correct graphic cards (non-volta)

**Comment by robotcator** [comment]
@tridao @lucidrains I see, it still builds locally not uploading the builded wheel package to `pypi-server`.

Previously, I created the workflow to build the wheel package and then uploading to release assert. Due to the `name format`, the built wheel can not upload to the 'pypi-server'

**Pull request merged**
